Update app.yaml
Change script type to auto due to error deploying new config

ERROR: (gcloud.app.deploy) INVALID_ARGUMENT: script field for handler '/.*' must be set to 'auto' for runtime nodejs8.